import React, { useState } from 'react';
import { View, Text, TouchableOpacity, ScrollView, ActivityIndicator, StyleSheet, Share } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Sparkles, Wand2, Copy, Share2, Quote } from 'lucide-react-native';
import * as Clipboard from 'expo-clipboard';
import { useTheme } from '../context/ThemeContext';

export default function AIScreen() {
    const { isDarkMode } = useTheme();
    const [loading, setLoading] = useState(false);
    const [shayari, setShayari] = useState("");

    const [form, setForm] = useState({
        Mood: "Happy",
        Purpose: "Life",
        Personality: "Poetic",
        Depth: "Medium",
    });

    const options = {
        Mood: ["Happy", "Sad", "Motivated", "Broken", "Romantic", "Angry"],
        Purpose: ["Love", "Motivation", "Life", "Hustle", "Friendship", "Success"],
        Personality: ["Calm", "Bold", "Emotional", "Poetic", "Witty"],
        Depth: ["Light", "Medium", "Deep", "Philosophical"],
    };

    const generateShayari = async () => {
        setLoading(true);
        setShayari("");

        try {
            const response = await fetch(`https://alfaaz-backend.vercel.app/api/shayari/generate`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    mood: form.Mood,
                    depth: form.Depth,
                    purpose: form.Purpose,
                    personality: form.Personality
                }),
            });

            const data = await response.json();
            if (data.shayari) {
                setShayari(data.shayari);
            } else {
                setShayari("The muse is silent right now. Please try again.");
            }
        } catch (err) {
            console.error(err);
            setShayari("Connection to the poetic realm failed. Check your internet.");
        } finally {
            setLoading(false);
        }
    };

    const copyToClipboard = async () => {
        if (!shayari) return;
        await Clipboard.setStringAsync(shayari);
        // Toast could be added here
    };

    const shareShayari = async () => {
        if (!shayari) return;
        try {
            await Share.share({
                message: shayari + '\n\n- Generated by Alfaaz AI',
            });
        } catch (error) {
            console.log(error);
        }
    };

    return (
        <View className={`flex-1 ${isDarkMode ? 'bg-black' : 'bg-gray-50'}`}>
            <StatusBar style={isDarkMode ? "light" : "dark"} translucent={true} backgroundColor="transparent" />
            <LinearGradient
                colors={isDarkMode ? ['#000000', '#050816', '#000000'] : ['#f9fafb', '#f3f4f6', '#f9fafb']}
                style={StyleSheet.absoluteFillObject}
            />

            <SafeAreaView className="flex-1">
                <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 100 }}>

                    {/* Header */}
                    <View className="items-center mb-6 mt-2">
                        <Text className="text-5xl font-bold tracking-tighter text-transparent" style={{ color: '#fbbf24' }}>
                            अल्फ़ाज़
                        </Text>
                        <Text className={`mt-2 text-center max-w-xs ${isDarkMode ? 'text-zinc-400' : 'text-gray-500'}`}>
                            Craft soulful poetry through the harmony of emotions and AI
                        </Text>
                    </View>

                    {/* Controls Panel */}
                    <View className={`p-5 rounded-3xl mb-8 border ${isDarkMode ? 'bg-white/5 border-white/10' : 'bg-white border-gray-200 shadow-sm'}`}>
                        {Object.entries(options).map(([key, values]) => (
                            <View key={key} className="mb-6">
                                <Text className={`text-xs uppercase tracking-widest font-bold mb-3 ml-1 ${isDarkMode ? 'text-zinc-500' : 'text-gray-400'}`}>
                                    {key}
                                </Text>
                                <ScrollView horizontal showsHorizontalScrollIndicator={false} className="flex-row gap-2">
                                    {values.map((v) => (
                                        <TouchableOpacity
                                            key={v}
                                            onPress={() => setForm({ ...form, [key]: v })}
                                            className={`px-4 py-2 rounded-full border mr-2 ${form[key] === v
                                                    ? 'bg-amber-400 border-amber-400'
                                                    : (isDarkMode ? 'bg-white/5 border-white/10' : 'bg-gray-50 border-gray-200')
                                                }`}
                                        >
                                            <Text className={`font-semibold ${form[key] === v
                                                    ? 'text-black'
                                                    : (isDarkMode ? 'text-zinc-400' : 'text-gray-600')
                                                }`}>
                                                {v}
                                            </Text>
                                        </TouchableOpacity>
                                    ))}
                                </ScrollView>
                            </View>
                        ))}

                        <TouchableOpacity
                            onPress={generateShayari}
                            disabled={loading}
                            className={`w-full py-4 rounded-xl items-center justify-center flex-row gap-2 ${loading ? 'opacity-70' : ''}`}
                            style={{
                                backgroundColor: loading ? '#3f3f46' : '#fbbf24',
                                shadowColor: '#fbbf24',
                                shadowOffset: { width: 0, height: 4 },
                                shadowOpacity: 0.3,
                                shadowRadius: 8,
                                elevation: 6
                            }}
                        >
                            {loading ? (
                                <>
                                    <ActivityIndicator color="white" />
                                    <Text className="text-white font-bold text-lg">Weaving Words...</Text>
                                </>
                            ) : (
                                <>
                                    <Wand2 color="black" size={20} />
                                    <Text className="text-black font-bold text-lg">Generate Shayari</Text>
                                </>
                            )}
                        </TouchableOpacity>
                    </View>

                    {/* Output Panel */}
                    <View className={`border rounded-3xl min-h-[300px] justify-center items-center p-6 ${isDarkMode ? 'bg-white/5 border-white/10' : 'bg-white border-gray-200 shadow-sm'}`}>
                        {shayari ? (
                            <View className="w-full">
                                <View className="items-center mb-6">
                                    <Quote size={32} color={isDarkMode ? "#fbbf24" : "#d97706"} style={{ opacity: 0.5 }} />
                                </View>

                                <Text className={`text-2xl font-serif text-center leading-loose mb-8 ${isDarkMode ? 'text-amber-50' : 'text-gray-800'}`}>
                                    {shayari}
                                </Text>

                                <View className={`flex-row justify-center gap-6 pt-6 border-t ${isDarkMode ? 'border-white/10' : 'border-gray-100'}`}>
                                    <TouchableOpacity
                                        onPress={copyToClipboard}
                                        className={`p-3 rounded-full ${isDarkMode ? 'bg-white/10 hover:bg-white/20' : 'bg-gray-100'}`}
                                    >
                                        <Copy size={20} color={isDarkMode ? "#fbbf24" : "#d97706"} />
                                    </TouchableOpacity>
                                    <TouchableOpacity
                                        onPress={shareShayari}
                                        className={`p-3 rounded-full ${isDarkMode ? 'bg-white/10 hover:bg-white/20' : 'bg-gray-100'}`}
                                    >
                                        <Share2 size={20} color={isDarkMode ? "#fbbf24" : "#d97706"} />
                                    </TouchableOpacity>
                                </View>
                            </View>
                        ) : (
                            <View className="items-center opacity-50">
                                <Sparkles size={48} color={isDarkMode ? "#fbbf24" : "#d97706"} style={{ marginBottom: 16 }} />
                                <Text className={`text-center ${isDarkMode ? 'text-zinc-500' : 'text-gray-400'}`}>
                                    Select your mood, purpose, personality and depth, {"\n"}then let the magic unfold.
                                </Text>
                            </View>
                        )}
                    </View>

                </ScrollView>
            </SafeAreaView>
        </View>
    );
}
